# sql的mapper的目录，配置sql打印
logging:
  level:
    net:
      codingme:
        boot:
          dao:
            mapper: debug
# mapper的orm对象映射，及不扫描的类
mapper:
  identity: MYSQL
  mappers: net.codingme.boot.dao.MybatisMapper
  not-empty: false
mybatis:
  configuration:
    aggressive-lazy-loading: false
    lazy-load-trigger-methods: equals,clone,hashCode
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.codingme.boot.domain
pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
restart:
  include:
    mapper: /mapper-[\w-\.]+jar
    pagehelper: /pagehelper-[\w-\.]+jar
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 5
    login-password: vap
    login-username: vap
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: 123456
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/spring?characterEncoding=utf-8&serverTimezone=GMT%2B8&useUnicode=true&useSSL=false&
    useGlobalDataSourceStat: true
    username: root
    validationQuery: SELECT 1 FROM DUAL
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev
